[template]
src = "bird6.cfg.template"
dest = "/config/bird6.cfg"
prefix = "/calico"
keys = [
    "/v1/ipam/v6/pool",
    "/bgp/v1/host",
    "/bgp/v1/global"
]
reload_cmd = "pkill -HUP bird6 || true"
